// Controllers
import '../../data/controllers/user.controller';
import '../../data/controllers/user-adress.controller';
import '../../data/controllers/card.controller';
import '../../data/controllers/company.controller';
import '../../data/controllers/company-adress.controller';
import '../../data/controllers/employee.controller';
import '../../data/controllers/payment.controller';
import '../../data/controllers/parking.controller';
import '../../data/controllers/vehicle.controller';
import '../../data/controllers/rule.controller';
import '../../data/controllers/parking-promotion.controller';
import '../../data/controllers/parking-space.controller';
import '../../data/controllers/parking-adress.controller';
import '../../data/controllers/scheduling.controller';
import '../../data/controllers/parking-score.controller';
import '../../data/controllers/parking-finance.controller';
import '../../data/controllers/auth.controller';
import '../../data/controllers/email.controller';